require.config({
    baseUrl:'/',
    paths:{
        jquery:'libs/jquery/jquery-1.12.4.min',
        loadHF:"js/loadHeaderAndFooter",
        swiper:"/libs/swiper/js/swiper.min",
        template:"/libs/art-template/template-web"
    }
})